In [1]:
# Código en Jupyter Notebook
# ====================================
# Ejemplo y descripciones en Markdown para las operaciones iniciales de NumPy.


# 1. Creación de Arrays
NumPy permite crear arrays de diferentes dimensiones, formas y tipos de datos. A continuación, veremos cómo crear:
- **Un array unidimensional (vector)**: Un array unidimensional es una lista ordenada de valores. Es como una fila de números en una tabla. Todos los elementos están en una sola dimensión (un "nivel"). Por ejemplo: una fila de asientos en un cine numerados del 1 al 10. 
- **Un array bidimensional (matriz)**: Un array bidimensional es una tabla de valores con filas y columnas. Cada elemento se identifica por su posición en la fila y la columna. Es como una hoja de Excel con datos distribuidos en varias celdas.Por ejemplo: una tabla de calificaciones donde cada fila representa un estudiante y cada columna representa una asignatura.
- **Un array tridimensional**: Un array tridimensional es un conjunto de matrices apiladas una sobre otra. Es como una colección de tablas bidimensionales que juntas forman un cubo de datos. Por ejemplo: un calendario con 12 páginas (una por mes). Cada página es una tabla con días de la semana y semanas del mes. Cuando juntas las 12 páginas, tienes un conjunto tridimensional.
- **Arrays llenos con ceros, unos, valores aleatorios o un rango específico**:  
  NumPy puede crear arrays predefinidos de diferentes tipos, como:  
  - **Ceros**: Una matriz en la que todos los elementos son `0`. Útil como base para cálculos. Ejemplo: inicializar las puntuaciones de los jugadores de un juego. 
  - **Unos**: Similar a la matriz de ceros, pero llena de `1`. Ejemplo: estás desarrollando un modelo de red neuronal y necesitas un vector de pesos iniciales.
  - **Valores aleatorios**: Una matriz con números generados al azar. Útil para simulaciones.  
  - **Rango específico**: Una secuencia de números con un intervalo definido.  
  - **Array de números aleatorios**: np.random.random() genera un array de números flotantes aleatorios entre 0 y
  - **Array de números aleatorios con np.random.rand()**: np.random.rand() también genera números aleatorios, pero es más sencillo de usar cuando se especifica el tamaño directamente.
  - **Array de números aleatorios enteros**: np.random.randint() genera números enteros aleatorios dentro de un rango específico.
  - **Array vacío**: np.empty() crea un array sin inicializar, lo que significa que los valores en el array no están definidos hasta que se les asignen.
  - **Array con valores espaciados**: np.linspace() genera un array con un número específico de puntos espaciados uniformemente entre dos valores.



In [ ]:
import numpy as np

# Array unidimensional
array_1d = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:", array_1d)

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array bidimensional:\n", array_2d)

# Array tridimensional
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Array tridimensional:\n", array_3d)

# Array de ceros
zeros = np.zeros((2, 3))
print("Array de ceros:\n", zeros)

# Creamos un array 2x4 de unos
pesos_iniciales = np.ones((2, 4))
print("Pesos iniciales:\n", pesos_iniciales)

# Array con un rango
range_array = np.arange(0, 10, 2)
print("Array con rango:\n", range_array)

# Array de números aleatorios
random_array = np.random.random((2, 2))
print("Array de números aleatorios:\n", random_array)

random_array_argumentos = np.random.rand(2, 3)
print(random_array_argumentos)

# Array de números aleatorios enteros
random_int_array = np.random.randint(0, 10, (2, 3)) #np.random.randint(0, 10, size=(2, 3))
print("Array de números aleatorios enteros:\n", random_int_array)

# Array vacío
empty_arr = np.empty((2, 2)) 
print(empty_arr)

# Array con valores espaciados
linspace_arr = np.linspace(0, 1, 5) # Empieza en 0, termina en 1, con 5 puntos en total
print(linspace_arr)
  

# 2. Indexación y Selección
Accede a elementos específicos, filas o columnas de un array utilizando índices. NumPy usa índices base 0 y permite seleccionar múltiples elementos mediante slices o índices específicos.

Esto es muy útil para manipular y analizar datos en IA, donde los arrays bidimensionales pueden representar cosas como:

- Imágenes (donde cada número es un píxel).
- Tablas de datos (cada fila es un ejemplo y cada columna, una característica).
- Redes neuronales (matrices de pesos y activaciones).


In [3]:
# Crear un array 1D
arr_1d = np.array([1, 2, 3, 4, 5])

# Indexación en un array 1D 
print(arr_1d[0]) # Primer elemento
print(arr_1d[-1]) # Último elemento

# Crear un array 2D (matriz)
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])

# Indexación en un array 2D
print(arr_2d[0, 0]) # Primer elemento de la primera fila 
print(arr_2d[1, 2]) # Tercer elemento de la segunda fila 
print(arr_2d[-1, -1]) # Último elemento de la última fila

# Selección de filas y columnas en un array 2D 
print(arr_2d[0, :]) # Primera fila 
print(arr_2d[:, 1]) # Segunda columna


Elemento en (1, 2): 60
Segunda fila: [40 50 60]
Primera columna: [10 40 70]


# 3. Slicing
Extrae subarrays o segmentos de un array utilizando rangos. Puedes definir el inicio, fin y el paso de los índices.

**np.arange** es una función de NumPy que crea un array unidimensional con una secuencia de números. Funciona como **range** en Python, pero devuelve un array en lugar de una lista.

Un slice es una forma de seleccionar una parte del array. En NumPy, lo hacemos con la sintaxis array[inicio:fin:paso]:
- Inicio: Índice donde empezar (por defecto, 0).
- Fin: Índice donde detenerse (sin incluirlo).
- Paso: Cuántos elementos saltar (por defecto, 1).


In [7]:
#np.arrange
rango_array = np.arange(5)
print("Rango array:", rango_array)
print("Rango específico array:", np.arange(2, 10))
print("Array con paso personalizado:", np.arange(0, 10, 2))
print("Array con paso decimal:", np.arange(0, 1, 0.2))
print("Array en orden inverso:", np.arange(10, 0, -1))


# Array unidimensional
array = np.arange(10)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Slice del índice 2 al 5
print("Slice [2:6]:", array[2:6])  # [2, 3, 4, 5]

# Slice con un paso de 2
print("Slice [::2]:", array[::2])  # "Empieza en el principio, llega hasta el final, y salta de 2 en 2" -> [0, 2, 4, 6, 8]

# Slice en arrays bidimensionales
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Slice de las primeras dos filas y dos columnas:\n", array_2d[:2, :2])

# Slicing en un array tridimensional
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  # Primer bloque (dimensión 0)
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # Segundo bloque (dimensión 1)
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]  # Tercer bloque (dimensión 2)
])

# Mostrar el array tridimensional completo
print("Array 3D completo:\n", array_3d)

# Slice: Seleccionar todo el primer bloque (dimensión 0)
print("\nPrimer bloque:\n", array_3d[0])

# Slice: Seleccionar la primera fila de cada bloque
print("\nPrimera fila de cada bloque:\n", array_3d[:, 0, :]) #: selecciona todos los bloques, 0 selecciona la primera fila de cada bloque, : selecciona todas las columnas.

# Slice: Seleccionar la primera columna de cada bloque
print("\nPrimera columna de cada bloque:\n", array_3d[:, :, 0])

# Slice: Seleccionar un elemento específico (bloque 2, fila 1, columna 2)
print("\nElemento en (2, 1, 2):", array_3d[2, 1, 2])  # 24


Rango array: [0 1 2 3 4]
Rango específico array: [2 3 4 5 6 7 8 9]
Array con paso personalizado: [0 2 4 6 8]
Array con paso decimal: [0.  0.2 0.4 0.6 0.8]
Array en orden inverso: [10  9  8  7  6  5  4  3  2  1]
Slice [2:6]: [2 3 4 5]
Slice [::2]: [0 2 4 6 8]
Slice de las primeras dos filas y dos columnas:
 [[1 2]
 [4 5]]


# 4. Manipulación de la Forma del Array
NumPy permite cambiar la forma de un array sin modificar sus datos mediante funciones como `reshape`, `ravel` y `transpose`.


In [5]:
# Array unidimensional
array = np.arange(12)  # [0, 1, ..., 11]

# Cambiar la forma a una matriz 3x4
reshaped = array.reshape(3, 4)
print("Array reshape (3x4):\n", reshaped)

# Aplanar el array a un vector
flattened = reshaped.ravel()
print("Array aplanado:", flattened)

# Transponer el array
transposed = reshaped.T
print("Array transpuesto:\n", transposed)


Array reshape (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array aplanado: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array transpuesto:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# 5. Operaciones Aritméticas
NumPy soporta operaciones aritméticas como suma, resta, multiplicación y división. Estas operaciones pueden realizarse entre arrays del mismo tamaño o entre un array y un escalar (broadcasting).


In [6]:
# Arrays de ejemplo
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Suma
print("Suma:", array1 + array2)

# Resta
print("Resta:", array1 - array2)

# Multiplicación
print("Multiplicación:", array1 * array2)

# División
print("División:", array1 / array2)

# Operación con un escalar
print("Array1 multiplicado por 2:", array1 * 2)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]
Array1 multiplicado por 2: [2 4 6]
